"""new report system

Revision ID: 11b2c1ff11c7
Revises: 38e76e46459b
Create Date: 2025-06-08 13:15:30.099432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b2c1ff11c7'
down_revision: Union[str, None] = '38e76e46459b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bottle', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('report_msg', sa.Column('bottle', sa.Integer(), nullable=False))
    op.add_column('report_msg', sa.Column('report_author', sa.BigInteger(), nullable=False))
    op.add_column('report_msg', sa.Column('is_closed', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'report_msg', 'bottle', ['bottle'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'report_msg', 'bot_user', ['report_author'], ['tg_id'])
    op.drop_column('report_msg', 'msg_id')
    op.drop_column('report_msg', 'report_id')
    op.drop_column('report_msg', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_msg', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('report_msg', sa.Column('report_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('report_msg', sa.Column('msg_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'report_msg', type_='foreignkey')
    op.drop_constraint(None, 'report_msg', type_='foreignkey')
    op.drop_column('report_msg', 'is_closed')
    op.drop_column('report_msg', 'report_author')
    op.drop_column('report_msg', 'bottle')
    op.drop_column('bottle', 'is_active')
    # ### end Alembic commands ###