"""update settings

Revision ID: 2c3a6ec74809
Revises: 11b2c1ff11c7
Create Date: 2025-06-08 21:02:15.794967

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c3a6ec74809"
down_revision: Union[str, None] = "11b2c1ff11c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usr_settings")
    op.add_column(
        "bot_user",
        sa.Column(
            "p_watch_answ_type",
            sa.String(length=10),
            server_default="new",
            nullable=False,
        ),
    )
    op.add_column(
        "bot_user",
        sa.Column(
            "p_send_rand", sa.String(length=10), server_default="true", nullable=False
        ),
    )
    op.add_column(
        "bot_user",
        sa.Column(
            "p_send_like", sa.String(length=10), server_default="true", nullable=False
        ),
    )
    op.add_column(
        "bot_user",
        sa.Column("p_bottle_exists", sa.Integer(), server_default="7", nullable=False),
    )
    op.add_column(
        "bot_user",
        sa.Column("p_bad_mode", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_user", "p_bad_mode")
    op.drop_column("bot_user", "p_bottle_exists")
    op.drop_column("bot_user", "p_send_like")
    op.drop_column("bot_user", "p_send_rand")
    op.drop_column("bot_user", "p_watch_answ_type")
    op.create_table(
        "usr_settings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("usr", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "p_like_notif",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "p_send_rand",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["usr"],
            ["bot_user.tg_id"],
            name="usr_settings_usr_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="usr_settings_pkey"),
    )
    # ### end Alembic commands ###
