"""bottle stats usr settings

Revision ID: 2d6c776da99d
Revises: 1526d1b56328
Create Date: 2025-06-06 16:45:18.250796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d6c776da99d"
down_revision: Union[str, None] = "1526d1b56328"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usr_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usr", sa.BigInteger(), nullable=False),
        sa.Column("p_like_notif", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("p_send_rand", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(["usr"], ["bot_user.tg_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_unique_constraint(None, "bot_user", ["id"])
    op.add_column(
        "bottle", sa.Column("likes", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "bottle",
        sa.Column("dislikes", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bottle", "dislikes")
    op.drop_column("bottle", "likes")
    op.drop_constraint(None, "bot_user", type_="unique")
    op.drop_table("usr_settings")
    # ### end Alembic commands ###
