"""initial

Revision ID: 3b83db18f7df
Revises: 
Create Date: 2025-09-30 11:06:30.027767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b83db18f7df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('send_lim', sa.Integer(), nullable=False),
    sa.Column('find_lim', sa.Integer(), nullable=False),
    sa.Column('send_amount', sa.Integer(), nullable=False),
    sa.Column('find_amount', sa.Integer(), nullable=False),
    sa.Column('receive_amount', sa.Integer(), nullable=False),
    sa.Column('likes_amount', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('rating_place', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bottles', sa.Integer(), nullable=False),
    sa.Column('warns', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('p_watch_answ_type', sa.String(length=10), server_default='new', nullable=False),
    sa.Column('p_send_rand', sa.String(length=10), server_default='true', nullable=False),
    sa.Column('p_send_like', sa.String(length=10), server_default='true', nullable=False),
    sa.Column('p_bottle_exists', sa.Integer(), server_default='7', nullable=False),
    sa.Column('p_bad_mode', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('online_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('bottle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=10), server_default='text', nullable=False),
    sa.Column('file_id', sa.Text(), server_default='', nullable=False),
    sa.Column('author', sa.BigInteger(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dislikes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('bad', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('related_bottle', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['bot_user.tg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_bottle'], ['bottle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.BigInteger(), nullable=False),
    sa.Column('bottle', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bottle'], ['bottle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person'], ['bot_user.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_msg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bottle', sa.Integer(), nullable=False),
    sa.Column('report_author', sa.BigInteger(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bottle'], ['bottle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_author'], ['bot_user.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.BigInteger(), nullable=False),
    sa.Column('bottle', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bottle'], ['bottle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person'], ['bot_user.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewed')
    op.drop_table('report_msg')
    op.drop_table('liked')
    op.drop_table('bottle')
    op.drop_table('ref_link')
    op.drop_table('online_info')
    op.drop_table('bot_user')
    # ### end Alembic commands ###