"""new answ system

Revision ID: 65b5a796f8ef
Revises: 6ea0a274f00e
Create Date: 2025-06-13 23:06:57.415830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65b5a796f8ef'
down_revision: Union[str, None] = '6ea0a274f00e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.add_column('bottle', sa.Column('related_bottle', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bottle', 'bottle', ['related_bottle'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bottle', type_='foreignkey')
    op.drop_column('bottle', 'related_bottle')
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bottle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author'], ['bot_user.tg_id'], name='answer_author_fkey'),
    sa.ForeignKeyConstraint(['bottle'], ['bottle.id'], name='answer_bottle_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='answer_pkey')
    )
    # ### end Alembic commands ###