"""bad bottle

Revision ID: 6ea0a274f00e
Revises: 2c3a6ec74809
Create Date: 2025-06-09 15:10:32.535496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ea0a274f00e"
down_revision: Union[str, None] = "2c3a6ec74809"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bottle", sa.Column("bad", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bottle", "bad")
    # ### end Alembic commands ###
