"""bottle multitypes

Revision ID: 6f312efe39a4
Revises: 5cafa02cee0b
Create Date: 2025-05-18 21:39:14.702782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f312efe39a4'
down_revision: Union[str, None] = '5cafa02cee0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bottle', sa.Column('type', sa.String(length=10), server_default='text', nullable=False))
    op.add_column('bottle', sa.Column('file_id', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bottle', 'file_id')
    op.drop_column('bottle', 'type')
    # ### end Alembic commands ###