"""report system

Revision ID: 8b0b7766ecc4
Revises: e27ad3a9d862
Create Date: 2025-05-17 23:12:52.313816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0b7766ecc4'
down_revision: Union[str, None] = 'e27ad3a9d862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_user', sa.Column('is_banned', sa.Boolean(), server_default='False', nullable=False))
    op.drop_column('bot_user', 'warns')
    op.drop_constraint('report_bottle_report_person_fkey', 'report_bottle', type_='foreignkey')
    op.drop_column('report_bottle', 'report_person')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_bottle', sa.Column('report_person', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('report_bottle_report_person_fkey', 'report_bottle', 'bot_user', ['report_person'], ['tg_id'])
    op.add_column('bot_user', sa.Column('warns', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bot_user', 'is_banned')
    # ### end Alembic commands ###