"""user rating

Revision ID: dd9d4af02312
Revises: 6f312efe39a4
Create Date: 2025-05-19 16:23:13.312403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd9d4af02312"
down_revision: Union[str, None] = "6f312efe39a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bot_user",
        sa.Column("rating_place", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_user", "rating_place")
    # ### end Alembic commands ###
