"""Initial

Revision ID: e27ad3a9d862
Revises:
Create Date: 2025-05-17 20:38:39.095787

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e27ad3a9d862"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user')
    # op.create_unique_constraint(None, 'bot_user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bot_user", type_="unique")
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("tg_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("send_today", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("receive_today", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "additional_bottles", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("send_amount", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("receive_amount", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("reputation", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="user_pkey"),
        sa.UniqueConstraint("tg_id", name="user_tg_id_key"),
    )
    # ### end Alembic commands ###
